"""Add first name and last name for user

Revision ID: 17633894cee2
Revises: 61161f74bd6d
Create Date: 2021-06-09 10:44:15.039395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17633894cee2'
down_revision = '61161f74bd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
