"""Add avatar for user

Revision ID: 270b396fddf7
Revises: 17633894cee2
Create Date: 2021-07-02 22:01:06.502146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270b396fddf7'
down_revision = '17633894cee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
