"""Connect video and course model

Revision ID: 344625e2f85d
Revises: 137245a2789f
Create Date: 2021-07-14 17:05:55.633495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '344625e2f85d'
down_revision = '137245a2789f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'video', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'course_id')
    # ### end Alembic commands ###
