"""Add more information in profile

Revision ID: 5a45c8b83b0e
Revises: 344625e2f85d
Create Date: 2021-07-27 20:48:14.947775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a45c8b83b0e'
down_revision = '344625e2f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
