"""Add category in course

Revision ID: fcb4a6a27ecd
Revises: 5a45c8b83b0e
Create Date: 2021-07-28 16:36:11.512979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb4a6a27ecd'
down_revision = '5a45c8b83b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'category')
    # ### end Alembic commands ###
